export const useBattleStore = defineStore('battle', {
    state: () => ({
        'littleGuys1': {
            enemies: [{
                name: "Little Guy 1",
                attack: 10,
                defense: 3,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 10,
                defense: 0,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }]
        },
        'battleKellan': {
            enemies: [{
                name: "Kellan (evil)",
                attack: 10,
                defense: 15,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 40,
                maxHP: 40,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kellan.png',
                expDrop: 35,
                desc: "Math, Basketball, Girls, he's got them... 2/3rds of them. Half of them.",
                level: 2,
                title: "JV Tryout Demon",
                sound: '/sounds/kellan.m4a',
            }]
        },

        'blockyBall1': {
            enemies: [{
                name: "Super Blocky Ball",
                attack: 15,
                defense: 7,
                abilityType: "offense",
                abilityName: "Ball Ram",
                ability: ballRam,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/superblockyball.png',
                expDrop: 35,
                desc: "Has a really good time on McManor and Tomb Ruins (Remastered).",
                level: 1,
                title: "Racer",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'battleNoure': {
            enemies: [{
                name: "Noure (evil)",
                attack: 15,
                defense: 8,
                abilityType: "offense",
                abilityName: "MultiWielding",
                ability: multiWielding,
                manaCost: 30,
                currentHP: 50,
                maxHP: 50,
                currentMana: 50,
                maxMana: 50,
                img: '/images/noure.png',
                expDrop: 35,
                desc: "Conspires against Edward even though they are on the same team.",
                level: 2,
                title: "Pain in Dev's Ass",
                sound: '/sounds/noure.caf',
            }]
        },

        'grassMan1': {
            enemies: [{
                name: "Grass Man 1",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            },{
                name: "Grass Man 2",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleHumd': {
            enemies: [{
                name: "Humd (evil, but not so evil)",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Mango Consumption",
                ability: mangoConsumption,
                manaCost: 30,
                currentHP: 60,
                maxHP: 60,
                currentMana: 35,
                maxMana: 35,
                img: '/images/humd.png',
                expDrop: 35,
                desc: "The best.",
                level: 2,
                title: "Lovely Partner",
                sound: '/sounds/humd.m4a',
            }]
        },

        'lemonAlien1': {
            enemies: [{
                name: "Lemon Alien",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Lemon Rebirth",
                ability: lemonRebirth,
                manaCost: 30,
                currentHP: 90,
                maxHP: 90,
                currentMana: 50,
                maxMana: 50,
                img: '/images/lemonalien.png',
                expDrop: 30,
                desc: "From another dimension seeking the finest of fruits.",
                level: 2,
                title: "Venture Capitalist",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleKortnee': {
            enemies: [{
                name: "Kortnee (evil)",
                attack: 30,
                defense: 10,
                abilityType: "offense",
                abilityName: "Moon Princess Halation",
                ability: moonPrincessHalation,
                manaCost: 60,
                currentHP: 120,
                maxHP: 120,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kortnee.png',
                expDrop: 45,
                desc: "Sometimes I don't really know what she's talking about.",
                level: 3,
                title: "Hachiware Fan",
                sound: '/sounds/kortnee.m4a',
            }]
        },

        'littleGuys2': {
            enemies: [{
                name: "Little Guy 1",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 3",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 4",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },]
        },



    } as Record<string, EnemyGroup>),
    actions: {

    }
})