import BuffLie from "~/components/animations/buff-lie.vue";

export const useBattleStore = defineStore('battle', {
    state: () => ({
        'littleGuys1': {
            enemies: [{
                name: "Little Guy 1",
                attack: 10,
                defense: 3,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 10,
                defense: 0,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }]
        },
        'battleKellan': {
            enemies: [{
                name: "Kellan (evil)",
                attack: 10,
                defense: 15,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 40,
                maxHP: 40,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kellan.png',
                expDrop: 35,
                desc: "Math, Basketball, Girls, he's got them... 2/3rds of them. Half of them.",
                level: 2,
                title: "JV Tryout Demon",
                sound: '/sounds/kellan.m4a',
            }]
        },

        'blockyBall1': {
            enemies: [{
                name: "Super Blocky Ball",
                attack: 15,
                defense: 7,
                abilityType: "offense",
                abilityName: "Ball Ram",
                ability: ballRam,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/superblockyball.png',
                expDrop: 35,
                desc: "Has a really good time on McManor and Tomb Ruins (Remastered).",
                level: 1,
                title: "Racer",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'battleNoure': {
            enemies: [{
                name: "Noure (evil)",
                attack: 15,
                defense: 8,
                abilityType: "offense",
                abilityName: "MultiWielding",
                ability: multiWielding,
                manaCost: 30,
                currentHP: 50,
                maxHP: 50,
                currentMana: 50,
                maxMana: 50,
                img: '/images/noure.png',
                expDrop: 35,
                desc: "Conspires against Edward even though they are on the same team.",
                level: 2,
                title: "Pain in Dev's Ass",
                sound: '/sounds/noure.caf',
            }]
        },

        'grassMan1': {
            enemies: [{
                name: "Grass Man 1",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            },{
                name: "Grass Man 2",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleHumd': {
            enemies: [{
                name: "Humd (evil, but not so evil)",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Mango Consumption",
                ability: mangoConsumption,
                manaCost: 30,
                currentHP: 60,
                maxHP: 60,
                currentMana: 35,
                maxMana: 35,
                img: '/images/humd.png',
                expDrop: 35,
                desc: "The best.",
                level: 2,
                title: "Lovely Partner",
                sound: '/sounds/humd.m4a',
            }]
        },

        'lemonAlien1': {
            enemies: [{
                name: "Lemon Alien",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Lemon Rebirth",
                ability: lemonRebirth,
                manaCost: 30,
                currentHP: 90,
                maxHP: 90,
                currentMana: 50,
                maxMana: 50,
                img: '/images/lemonalien.png',
                expDrop: 30,
                desc: "From another dimension seeking the finest of fruits.",
                level: 2,
                title: "Venture Capitalist",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleKortnee': {
            enemies: [{
                name: "Kortnee (evil)",
                attack: 30,
                defense: 10,
                abilityType: "offense",
                abilityName: "Moon Princess Halation",
                ability: moonPrincessHalation,
                manaCost: 60,
                currentHP: 120,
                maxHP: 120,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kortnee.png',
                expDrop: 45,
                desc: "Sometimes I don't really know what she's talking about.",
                level: 3,
                title: "Hachiware Fan",
                sound: '/sounds/kortnee.m4a',
            }]
        },

        'littleGuys2': {
            enemies: [{
                name: "Little Guy 1",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 3",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 4",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },]
        },

        'miniCrossword1': {
            enemies: [{
                name: "Mini Crossword",
                attack: 10,
                defense: 15,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 90,
                maxHP: 90,
                currentMana: 100,
                maxMana: 100,
                img: '/images/mini-crossword.png',
                expDrop: 65,
                desc: "#FreeTheMini",
                level: 3,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleGil': {
            enemies: [{
                name: "Gil (evil)",
                attack: 25,
                defense: 25,
                abilityType: "defense",
                abilityName: "Buff Lie",
                ability: buffLie,
                manaCost: 50,
                currentHP: 140,
                maxHP: 140,
                currentMana: 100,
                maxMana: 100,
                img: '/images/gil.png',
                expDrop: 65,
                desc: "Seems pretty cool but egos me too much :/",
                level: 3,
                title: "Unresponsive Boyfriend Haver",
                sound: '/sounds/gil.m4a',
            }]
        },

        'battleGav': {
            enemies: [{
                name: "Gavin (evil)",
                attack: 25,
                defense: 25,
                abilityType: "offense",
                abilityName: "Make it Wild",
                ability: makeItWild,
                manaCost: 50,
                currentHP: 140,
                maxHP: 140,
                currentMana: 100,
                maxMana: 100,
                img: '/images/gavin.png',
                expDrop: 65,
                desc: "Your cousin.",
                level: 4,
                title: "Responsive Boyfriend Is-er",
                sound: '/sounds/gavin.m4a',
            }]
        },

        'alastor1': {
            enemies: [{
                name: "Alastor",
                attack: 35,
                defense: 20,
                abilityType: "offense",
                abilityName: "Minion Summon",
                ability: minionSummon,
                manaCost: 70,
                currentHP: 130,
                maxHP: 130,
                currentMana: 100,
                maxMana: 100,
                img: '/images/alastor.png',
                expDrop: 50,
                desc: "Hater of TV and Hated by U/Me",
                level: 4,
                title: "Radio Demon",
                sound: '/sounds/alastor.m4a',
            }]
        },

        'battleGab': {
            enemies: [{
                name: "Gab (evil)",
                attack: 35,
                defense: 15,
                abilityType: "defense",
                abilityName: "Magically Touch Nose With Tongue",
                ability: magicNoseTongueTouch,
                manaCost: 50,
                currentHP: 150,
                maxHP: 150,
                currentMana: 120,
                maxMana: 120,
                img: '/images/gab.png',
                expDrop: 65,
                desc: "Your sister. Where did the 'stinky' moniker come from anyway?",
                level: 3,
                title: "Sister",
                sound: '/sounds/gab.m4a',
            }]
        },

        'battleMom': {
            enemies: [{
                name: "Mrs. Paula Vento (evil)",
                attack: 20,
                defense: 35,
                abilityType: "defense",
                abilityName: "Mind Clear",
                ability: mindClear,
                manaCost: 60,
                currentHP: 160,
                maxHP: 160,
                currentMana: 120,
                maxMana: 120,
                img: '/images/mrspaulavento.png',
                expDrop: 65,
                desc: "Your mother. Been there since the start.",
                level: 4,
                title: "Mother",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'circle1': {
            enemies: [{
                name: "Circle 1",
                attack: 20,
                defense: 20,
                abilityType: "offense",
                abilityName: "Circle Smash",
                ability: circleSmash,
                manaCost: 70,
                currentHP: 80,
                maxHP: 80,
                currentMana: 120,
                maxMana: 120,
                img: '/images/circle.png',
                expDrop: 65,
                desc: "She's in my area because I... errr squared the pi.",
                level: 4,
                title: "Incrementalite",
                sound: '/sounds/baselow.caf',
            },{
                name: "Circle 2",
                attack: 20,
                defense: 20,
                abilityType: "offense",
                abilityName: "Circle Smash",
                ability: circleSmash,
                manaCost: 70,
                currentHP: 80,
                maxHP: 80,
                currentMana: 120,
                maxMana: 120,
                img: '/images/circle.png',
                expDrop: 65,
                desc: "She's in my area because I... errr squared the pi.",
                level: 4,
                title: "Incrementalite",
                sound: '/sounds/baselow.caf',
            }]
        },

        'miniCrossword2': {
            enemies: [{
                name: "Mini Crossword 1",
                attack: 25,
                defense: 5,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 60,
                maxHP: 60,
                currentMana: 90,
                maxMana: 90,
                img: '/images/mini-crossword.png',
                expDrop: 55,
                desc: "#FreeTheMini",
                level: 4,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            },{
                name: "Mini Crossword 2",
                attack: 25,
                defense: 5,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 60,
                maxHP: 60,
                currentMana: 90,
                maxMana: 90,
                img: '/images/mini-crossword.png',
                expDrop: 55,
                desc: "#FreeTheMini",
                level: 4,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            }]
        },

        'rtGame1': {
            enemies: [{
                name: "RT Game",
                attack: 40,
                defense: 30,
                abilityType: "offense",
                abilityName: "Drifting",
                ability: drifting,
                manaCost: 70,
                currentHP: 150,
                maxHP: 150,
                currentMana: 120,
                maxMana: 120,
                img: '/images/rtgame.png',
                expDrop: 65,
                desc: "That's what they called him back in HIGH SCHOOL.",
                level: 5,
                title: "Drift King",
                sound: '/sounds/baselow.caf',
            }]
        },

        'edward1': {
            enemies: [{
                name: "Edward (evil)",
                attack: 50,
                defense: 30,
                abilityType: "offense",
                abilityName: "THE SLAYER",
                ability: theSlayer,
                manaCost: 80,
                currentHP: 400,
                maxHP: 400,
                currentMana: 120,
                maxMana: 120,
                img: '/images/edwardevil.png',
                expDrop: 120,
                desc: "This fight is being coded at hour ~60 of the development process.",
                level: 7,
                title: "Developer, Friend, and SLAYER",
                sound: '/sounds/edward.caf',
            }]
        },

        'alastor2': {
            enemies: [{
                name: "Alastor",
                attack: 45,
                defense: 40,
                abilityType: "offense",
                abilityName: "Minion Summon",
                ability: minionSummon,
                manaCost: 70,
                currentHP: 200,
                maxHP: 200,
                currentMana: 120,
                maxMana: 120,
                img: '/images/alastor.png',
                expDrop: 70,
                desc: "Hater of TV and Hated by U/Me",
                level: 6,
                title: "Radio Demon",
                sound: '/sounds/alastor.m4a',
            }]
        },

        'waldo': {
            enemies: [{
                name: "Waldo",
                attack: 2,
                defense: 95,
                abilityType: "defense",
                abilityName: "Hide",
                ability: hide,
                manaCost: 70,
                currentHP: 100,
                maxHP: 100,
                currentMana: 120,
                maxMana: 120,
                img: '/images/waldo.png',
                expDrop: 100,
                desc: "Master of the Little Guys.",
                level: 6,
                title: "Hidden Figure",
                sound: '/sounds/baselow.caf',
            },{
                name: "Little Guy 4",
                attack: 20,
                defense: 25,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 100,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 50,
                desc: "Ready for one last shot at Joey.",
                level: 6,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 3",
                attack: 20,
                defense: 25,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 100,
                maxHP: 100,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 50,
                desc: "Avenging Little Guy 2. He didn't make it out of last time.",
                level: 5,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'battleLucia': {
            enemies: [{
                name: "Lucia (evil)",
                attack: 30,
                defense: 40,
                abilityType: "defense",
                abilityName: "Revive Song",
                ability: reviveSong,
                manaCost: 40,
                currentHP: 250,
                maxHP: 250,
                currentMana: 40,
                maxMana: 40,
                img: '/images/lucia.png',
                expDrop: 100,
                desc: "What an asshole man.",
                level: 6,
                title: "Unfunny Person",
                sound: '/sounds/lucia.m4a',
            }]
        },
        'battleThira': {
            enemies: [{
                name: "Thira (evil)",
                attack: 34,
                defense: 38,
                abilityType: "defense",
                abilityName: "Time Reversal",
                ability: timeReversal,
                manaCost: 50,
                currentHP: 250,
                maxHP: 250,
                currentMana: 120,
                maxMana: 120,
                img: '/images/thira.png',
                expDrop: 100,
                desc: "Likes watches? I never really new her to be honest.",
                level: 6,
                title: "Time Keeper",
                sound: '/sounds/thira.m4a',
            }]
        },
        'battleMatteo': {
            enemies: [{
                name: "Matteo (evil)",
                attack: 45,
                defense: 25,
                abilityType: "offense",
                abilityName: "You Tell Me",
                ability: youTellMe,
                manaCost: 50,
                currentHP: 350,
                maxHP: 350,
                currentMana: 180,
                maxMana: 180,
                img: '/images/matteo.png',
                expDrop: 100,
                desc: "stinky stinky stinky stinky stinky stinky stinky stinky stinky",
                level: 8,
                title: "Royal Crown Employee",
                sound: '/sounds/baselow.caf',
            }]
        },
        'maidenOLuck1': {
            enemies: [{
                name: "Maiden O' Luck 1",
                attack: 25,
                defense: 25,
                abilityType: "offense",
                abilityName: "Make it Wild",
                ability: makeItWild,
                manaCost: 50,
                currentHP: 170,
                maxHP: 170,
                currentMana: 180,
                maxMana: 180,
                img: '/images/maiden-o-luck.webp',
                expDrop: 100,
                desc: "The worst horse. Old money horse. Never worked a day in his life horse.",
                level: 6,
                title: "Racer",
                sound: '/sounds/maidenoluck.m4a',
            },{
                name: "Maiden O' Luck 2",
                attack: 25,
                defense: 25,
                abilityType: "offense",
                abilityName: "Make it Wild",
                ability: makeItWild,
                manaCost: 50,
                currentHP: 170,
                maxHP: 170,
                currentMana: 180,
                maxMana: 180,
                img: '/images/maiden-o-luck.webp',
                expDrop: 100,
                desc: "The worst horse. Old money horse. Never worked a day in his life horse.",
                level: 6,
                title: "Racer",
                sound: '/sounds/maidenoluck.m4a',
            }]
        },
        'rtGame2': {
            enemies: [{
                name: "RT Game",
                attack: 40,
                defense: 40,
                abilityType: "offense",
                abilityName: "Drifting",
                ability: drifting,
                manaCost: 70,
                currentHP: 300,
                maxHP: 300,
                currentMana: 160,
                maxMana: 160,
                img: '/images/rtgame.png',
                expDrop: 90,
                desc: "That's what they called him back in HIGH SCHOOL.",
                level: 7,
                title: "Drift King",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleColumbo': {
            enemies: [{
                name: "Columbo (evil)",
                attack: 30,
                defense: 40,
                abilityType: "offense",
                abilityName: "Examine",
                ability: examine,
                manaCost: 40,
                currentHP: 250,
                maxHP: 250,
                currentMana: 40,
                maxMana: 40,
                img: '/images/columbo.png',
                expDrop: 100,
                desc: "The world's greatest detective. Not better than L though.",
                level: 6,
                title: "Detective",
                sound: '/sounds/columbo.m4a',
            }]
        },

        'blockyBall2': {
            enemies: [{
                name: "Super Blocky Ball",
                attack: 30,
                defense: 27,
                abilityType: "offense",
                abilityName: "Ball Ram",
                ability: ballRam,
                manaCost: 25,
                currentHP: 170,
                maxHP: 170,
                currentMana: 50,
                maxMana: 50,
                img: '/images/superblockyball.png',
                expDrop: 65,
                desc: "Is ranked 47th in the world on Slime Factory",
                level: 6,
                title: "Racer",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Grass Man",
                attack: 30,
                defense: 27,
                abilityType: "offense",
                abilityName: "Ball Ram",
                ability: ballRam,
                manaCost: 25,
                currentHP: 170,
                maxHP: 170,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 65,
                desc: "Definitely an NFT.",
                level: 6,
                title: "Racer",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'battlePierce': {
            enemies: [{
                name: "Pierce (evil)",
                attack: 30,
                defense: 40,
                abilityType: "offense",
                abilityName: "Meta Narrative",
                ability: metaNarrative,
                manaCost: 40,
                currentHP: 250,
                maxHP: 250,
                currentMana: 40,
                maxMana: 40,
                img: '/images/pierce.png',
                expDrop: 100,
                desc: "The world's greatest detective. Not better than L though.",
                level: 6,
                title: "Detective",
                sound: '/sounds/pierce.m4a',
            }]
        },
        'greenBoys': {
            enemies: [{
                name: "Maiden O' Luck",
                attack: 40,
                defense: 35,
                abilityType: "offense",
                abilityName: "Make it Wild",
                ability: makeItWild,
                manaCost: 70,
                currentHP: 230,
                maxHP: 230,
                currentMana: 200,
                maxMana: 200,
                img: '/images/maiden-o-luck.webp',
                expDrop: 100,
                desc: "The worst horse. Old money horse. Never worked a day in his life horse.",
                level: 8,
                title: "Racer",
                sound: '/sounds/maidenoluck.m4a',
            },{
                name: "Grass Man",
                attack: 45,
                defense: 30,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 100,
                currentHP: 150,
                maxHP: 150,
                currentMana: 150,
                maxMana: 150,
                img: '/images/grassman.png',
                expDrop: 100,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 7,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleWoz': {
            enemies: [{
                name: "Scott the Woz (evil)",
                attack: 30,
                defense: 40,
                abilityType: "offense",
                abilityName: "Wii Game Wollop",
                ability: wiiGameWollop,
                manaCost: 100,
                currentHP: 250,
                maxHP: 250,
                currentMana: 200,
                maxMana: 200,
                img: '/images/scottthewoz.png',
                expDrop: 100,
                desc: "The slayer of the border.",
                level: 8,
                title: "Virgin",
                sound: '/sounds/scottthewoz.m4a',
            }]
        },

        'joeBidenSandman': {
            enemies: [{
                name: "Joe Biden",
                attack: 50,
                defense: 25,
                abilityType: "offense",
                abilityName: "Presidential Authority",
                ability: joeBidenSandman,
                manaCost: 100,
                currentHP: 400,
                maxHP: 400,
                currentMana: 200,
                maxMana: 200,
                img: '/images/joebiden.png',
                expDrop: 180,
                desc: "The strongest rap battle of history.",
                level: 7,
                title: "Sleepyhead",
                sound: '/sounds/joebiden.m4a',
            }]
        },

        'battleEdward': {
            enemies: [{
                name: "Edward (evil)",
                attack: 60,
                defense: 45,
                abilityType: "offense",
                abilityName: "THE SLAYER",
                ability: theSlayer,
                manaCost: 100,
                currentHP: 750,
                maxHP: 750,
                currentMana: 250,
                maxMana: 250,
                img: '/images/edwardevil.png',
                expDrop: 300,
                desc: "This fight is being coded at ~hour 80 of the coding process.",
                level: 12,
                title: "Developer, Friend, and SLAYER",
                sound: '/sounds/edward.caf',
            }]
        },

        'battleJoevil': {
            enemies: [{
                name: "Joevil (BOSS)",
                attack: 70,
                defense: 45,
                abilityType: "offense",
                abilityName: "Reign of Evil",
                ability: evilReign,
                manaCost: 100,
                currentHP: 400,
                maxHP: 400,
                currentMana: 300,
                maxMana: 300,
                img: '/images/joevil.png',
                expDrop: 300,
                desc: "This is the end.",
                level: 16,
                title: "Birthday Bane",
                sound: '/sounds/joey.m4a',
            }]
        },
        

    } as Record<string, EnemyGroup>),
    actions: {

    }
})