import BuffLie from "~/components/animations/buff-lie.vue";

export const useBattleStore = defineStore('battle', {
    state: () => ({
        'littleGuys1': {
            enemies: [{
                name: "Little Guy 1",
                attack: 10,
                defense: 3,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 10,
                defense: 0,
                abilityType: "defense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 20,
                maxHP: 20,
                currentMana: 50,
                maxMana: 50,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "A guy so little he's hard to find.",
                level: 1,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }]
        },
        'battleKellan': {
            enemies: [{
                name: "Kellan (evil)",
                attack: 10,
                defense: 15,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 40,
                maxHP: 40,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kellan.png',
                expDrop: 35,
                desc: "Math, Basketball, Girls, he's got them... 2/3rds of them. Half of them.",
                level: 2,
                title: "JV Tryout Demon",
                sound: '/sounds/kellan.m4a',
            }]
        },

        'blockyBall1': {
            enemies: [{
                name: "Super Blocky Ball",
                attack: 15,
                defense: 7,
                abilityType: "offense",
                abilityName: "Ball Ram",
                ability: ballRam,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/superblockyball.png',
                expDrop: 35,
                desc: "Has a really good time on McManor and Tomb Ruins (Remastered).",
                level: 1,
                title: "Racer",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'battleNoure': {
            enemies: [{
                name: "Noure (evil)",
                attack: 15,
                defense: 8,
                abilityType: "offense",
                abilityName: "MultiWielding",
                ability: multiWielding,
                manaCost: 30,
                currentHP: 50,
                maxHP: 50,
                currentMana: 50,
                maxMana: 50,
                img: '/images/noure.png',
                expDrop: 35,
                desc: "Conspires against Edward even though they are on the same team.",
                level: 2,
                title: "Pain in Dev's Ass",
                sound: '/sounds/noure.caf',
            }]
        },

        'grassMan1': {
            enemies: [{
                name: "Grass Man 1",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            },{
                name: "Grass Man 2",
                attack: 19,
                defense: 7,
                abilityType: "offense",
                abilityName: "Grass Cutting",
                ability: grassCut,
                manaCost: 25,
                currentHP: 40,
                maxHP: 40,
                currentMana: 50,
                maxMana: 50,
                img: '/images/grassman.png',
                expDrop: 20,
                desc: "Grass 'Cutting Incremental' Man. Is this an NFT?",
                level: 2,
                title: "Grassy Boy",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleHumd': {
            enemies: [{
                name: "Humd (evil, but not so evil)",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Mango Consumption",
                ability: mangoConsumption,
                manaCost: 30,
                currentHP: 60,
                maxHP: 60,
                currentMana: 35,
                maxMana: 35,
                img: '/images/humd.png',
                expDrop: 35,
                desc: "The best.",
                level: 2,
                title: "Lovely Partner",
                sound: '/sounds/humd.m4a',
            }]
        },

        'lemonAlien1': {
            enemies: [{
                name: "Lemon Alien",
                attack: 10,
                defense: 15,
                abilityType: "defense",
                abilityName: "Lemon Rebirth",
                ability: lemonRebirth,
                manaCost: 30,
                currentHP: 90,
                maxHP: 90,
                currentMana: 50,
                maxMana: 50,
                img: '/images/lemonalien.png',
                expDrop: 30,
                desc: "From another dimension seeking the finest of fruits.",
                level: 2,
                title: "Venture Capitalist",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleKortnee': {
            enemies: [{
                name: "Kortnee (evil)",
                attack: 30,
                defense: 10,
                abilityType: "offense",
                abilityName: "Moon Princess Halation",
                ability: moonPrincessHalation,
                manaCost: 60,
                currentHP: 120,
                maxHP: 120,
                currentMana: 100,
                maxMana: 100,
                img: '/images/kortnee.png',
                expDrop: 45,
                desc: "Sometimes I don't really know what she's talking about.",
                level: 3,
                title: "Hachiware Fan",
                sound: '/sounds/kortnee.m4a',
            }]
        },

        'littleGuys2': {
            enemies: [{
                name: "Little Guy 1",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            }, {
                name: "Little Guy 2",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Still hurt from your last encounter.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 3",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },{
                name: "Little Guy 4",
                attack: 13,
                defense: 6,
                abilityType: "offense",
                abilityName: "Shrink",
                ability: shrink,
                manaCost: 20,
                currentHP: 23,
                maxHP: 23,
                currentMana: 60,
                maxMana: 60,
                img: '/images/littleguys.png',
                expDrop: 20,
                desc: "Ready to help out Little Guys 1 and 2.",
                level: 2,
                title: "Smallish Person",
                sound: '/sounds/basehigh.m4a',
            },]
        },

        'miniCrossword1': {
            enemies: [{
                name: "Mini Crossword",
                attack: 10,
                defense: 15,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 90,
                maxHP: 90,
                currentMana: 100,
                maxMana: 100,
                img: '/images/mini-crossword.png',
                expDrop: 65,
                desc: "#FreeTheMini",
                level: 3,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            }]
        },

        'battleGil': {
            enemies: [{
                name: "Gil",
                attack: 25,
                defense: 25,
                abilityType: "defense",
                abilityName: "Buff Lie",
                ability: buffLie,
                manaCost: 50,
                currentHP: 140,
                maxHP: 140,
                currentMana: 100,
                maxMana: 100,
                img: '/images/gil.png',
                expDrop: 65,
                desc: "Seems pretty cool but egos me too much :/",
                level: 3,
                title: "Unresponsive Boyfriend Haver",
                sound: '/sounds/gil.m4a',
            }]
        },

        'battleGav': {
            enemies: [{
                name: "Gavin",
                attack: 25,
                defense: 25,
                abilityType: "offense",
                abilityName: "Make it Wild",
                ability: makeItWild,
                manaCost: 50,
                currentHP: 140,
                maxHP: 140,
                currentMana: 100,
                maxMana: 100,
                img: '/images/gavin.png',
                expDrop: 65,
                desc: "Your cousin.",
                level: 4,
                title: "Responsive Boyfriend Is-er",
                sound: '/sounds/gavin.m4a',
            }]
        },

        'alastor1': {
            enemies: [{
                name: "Alastor",
                attack: 35,
                defense: 20,
                abilityType: "offense",
                abilityName: "Minion Summon",
                ability: minionSummon,
                manaCost: 70,
                currentHP: 130,
                maxHP: 130,
                currentMana: 100,
                maxMana: 100,
                img: '/images/alastor.png',
                expDrop: 50,
                desc: "Hater of TV and Hated by U/Me",
                level: 4,
                title: "Radio Demon",
                sound: '/sounds/alastor.m4a',
            }]
        },

        'battleGab': {
            enemies: [{
                name: "Gab",
                attack: 35,
                defense: 15,
                abilityType: "defense",
                abilityName: "Magically Touch Nose With Tongue",
                ability: magicNoseTongueTouch,
                manaCost: 50,
                currentHP: 150,
                maxHP: 150,
                currentMana: 120,
                maxMana: 120,
                img: '/images/gab.png',
                expDrop: 65,
                desc: "Your sister. Where did the 'stinky' moniker come from anyway?",
                level: 3,
                title: "Sister",
                sound: '/sounds/gab.m4a',
            }]
        },

        'battleMom': {
            enemies: [{
                name: "Mrs. Paula Vento",
                attack: 20,
                defense: 35,
                abilityType: "defense",
                abilityName: "Mind Clear",
                ability: mindClear,
                manaCost: 60,
                currentHP: 160,
                maxHP: 160,
                currentMana: 120,
                maxMana: 120,
                img: '/images/mrspaulavento.png',
                expDrop: 65,
                desc: "Your mother. Been there since the start.",
                level: 4,
                title: "Mother",
                sound: '/sounds/basehigh.m4a',
            }]
        },

        'circle1': {
            enemies: [{
                name: "Circle 1",
                attack: 20,
                defense: 20,
                abilityType: "offense",
                abilityName: "Circle Smash",
                ability: circleSmash,
                manaCost: 70,
                currentHP: 80,
                maxHP: 80,
                currentMana: 120,
                maxMana: 120,
                img: '/images/circle.png',
                expDrop: 65,
                desc: "She's in my area because I... errr squared the pi.",
                level: 4,
                title: "Incrementalite",
                sound: '/sounds/baselow.caf',
            },{
                name: "Circle 2",
                attack: 20,
                defense: 20,
                abilityType: "offense",
                abilityName: "Circle Smash",
                ability: circleSmash,
                manaCost: 70,
                currentHP: 80,
                maxHP: 80,
                currentMana: 120,
                maxMana: 120,
                img: '/images/circle.png',
                expDrop: 65,
                desc: "She's in my area because I... errr squared the pi.",
                level: 4,
                title: "Incrementalite",
                sound: '/sounds/baselow.caf',
            }]
        },

        'miniCrossword2': {
            enemies: [{
                name: "Mini Crossword 1",
                attack: 25,
                defense: 5,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 60,
                maxHP: 60,
                currentMana: 90,
                maxMana: 90,
                img: '/images/mini-crossword.png',
                expDrop: 55,
                desc: "#FreeTheMini",
                level: 3,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            },{
                name: "Mini Crossword 2",
                attack: 25,
                defense: 5,
                abilityType: "offense",
                abilityName: "Quick Puzzle Confusion",
                ability: miniCrossword,
                manaCost: 60,
                currentHP: 60,
                maxHP: 60,
                currentMana: 90,
                maxMana: 90,
                img: '/images/mini-crossword.png',
                expDrop: 55,
                desc: "#FreeTheMini",
                level: 3,
                title: "NYT Puzzle Kid",
                sound: '/sounds/baselow.caf',
            }]
        },

        'rtGame1': {
            enemies: [{
                name: "RT Game",
                attack: 40,
                defense: 30,
                abilityType: "offense",
                abilityName: "Drifting",
                ability: drifting,
                manaCost: 70,
                currentHP: 150,
                maxHP: 150,
                currentMana: 120,
                maxMana: 120,
                img: '/images/rtgame.png',
                expDrop: 65,
                desc: "That's what they called him back in HIGH SCHOOL.",
                level: 4,
                title: "Drift King",
                sound: '/sounds/baselow.caf',
            }]
        },

        'edward1': {
            enemies: [{
                name: "Edward (evil)",
                attack: 50,
                defense: 30,
                abilityType: "offense",
                abilityName: "THE SLAYER",
                ability: theSlayer,
                manaCost: 80,
                currentHP: 400,
                maxHP: 400,
                currentMana: 120,
                maxMana: 120,
                img: '/images/edwardevil.png',
                expDrop: 120,
                desc: "This fight is being coded at hour ~60 of the development process.",
                level: 4,
                title: "Developer, Friend, and SLAYER",
                sound: '/sounds/edward.caf',
            }]
        },

    } as Record<string, EnemyGroup>),
    actions: {

    }
})