export const useFriendsStore = defineStore('friends', {
    state: () => ({
        "Joey": {
            name: "Joey",
            eachTurnCheck: null,
            abilityName: "Birthday Beam",
            abilityDesc: "Show em the power of birthday, king.",
            abilityTiming: "With Attack",
            targetType: "AOE",
            spriteURL: "/images/joey.png",
            sound: "/sounds/joey.m4a",
            ability: birthdayBeam,
            manaCost: 0
        } as Friend,
        "Gab": {
            name: "Gab",
            eachTurnCheck: null,
            abilityName: "Magically Touch Nose With Tongue",
            abilityDesc: "Touch your nose with your tongue. Magically. Confuse the target.",
            abilityTiming: "Before Turn",
            targetType: "Single",
            spriteURL: "/images/gab.png",
            sound: "/sounds/gab.m4a",
            ability: magicNoseTongueTouch,
            manaCost: 60
        } as Friend,
        "Gavin": {
            name: "Gavin",
            eachTurnCheck: null,
            abilityName: "Make it Wild",
            abilityDesc: "Randomize all stats.",
            abilityTiming: "With Attack",
            targetType: "AOE",
            spriteURL: "/images/gavin.png",
            sound: "/sounds/gavin.m4a",
            ability: makeItWild,
            manaCost: 15
        } as Friend,
        "Noure": {
            name: "Noure",
            eachTurnCheck: null,
            abilityName: "MultiWielding",
            abilityDesc: "Hit three times, with decreasing power.",
            abilityTiming: "With Attack",
            targetType: "Single",
            spriteURL: "/images/noure.png",
            sound: "/sounds/noure.m4a",
            ability: multiWielding,
            manaCost: 40
        } as Friend,
        "Kortnee": {
            name: "Kortnee",
            eachTurnCheck: null,
            abilityName: "Moon Princess Halation",
            abilityDesc: "Hit enemies with a massive AOE beam of light.",
            abilityTiming: "With Attack",
            targetType: "AOE",
            spriteURL: "/images/kortnee.png",
            sound: "/sounds/kortnee.m4a",
            ability: moonPrincessHalation,
            manaCost: 60
        } as Friend,
        "Matteo": {
            name: "Matteo",
            eachTurnCheck: null,
            abilityName: "You Tell Me",
            abilityDesc: "Use a random one of your friends' attacks.",
            abilityTiming: "After Turn",
            targetType: "Self",
            spriteURL: "/images/matteo.png",
            sound: "/sounds/matteo.m4a",
            ability: youTellMe,
            manaCost: 40
        } as Friend,
        "Mrs. Paula Vento": {
            name: "Mrs. Paula Vento",
            eachTurnCheck: null,
            abilityName: "Mind Clear",
            abilityDesc: "Clears your statuses and heals you.",
            abilityTiming: "With Attack",
            targetType: "Self",
            spriteURL: "/images/mrspaulavento.png",
            sound: "/sounds/basehigh.m4a",
            ability: mindClear,
            manaCost: 40
        } as Friend,
        "Pierce": {
            name: "Pierce",
            eachTurnCheck: null,
            abilityName: "Meta Narrative",
            abilityDesc: "Copies everything that has happened in the turn before this ability.",
            abilityTiming: "After Turn",
            targetType: "Special",
            spriteURL: "/images/pierce.png",
            sound: "/sounds/pierce.m4a",
            ability: metaNarrative,
            manaCost: 50
        } as Friend,
        "Scott the Woz": {
            name: "Scott the Woz",
            eachTurnCheck: null,
            abilityName: "Wii Game Wollop",
            abilityDesc: "Hit your enemies with many Wii Games.",
            abilityTiming: "With Attack",
            targetType: "AOE",
            spriteURL: "/images/scottthewoz.png",
            sound: "/sounds/scottthewoz.m4a",
            ability: wiiGameWollop,
            manaCost: 80
        } as Friend,
        "Gil": {
            name: "Gil",
            eachTurnCheck: null,
            abilityName: "Buff Lie",
            abilityDesc: "40% chance to give a random stat boost.",
            abilityTiming: "With Attack",
            targetType: "Self",
            spriteURL: "/images/gil.png",
            sound: "/sounds/gil.m4a",
            ability: buffLie,
            manaCost: 35
        } as Friend,
        "Kellan": {
            name: "Kellan",
            eachTurnCheck: null,
            abilityName: "Shrink",
            abilityDesc: "(shrink)",
            abilityTiming: "With Attack",
            targetType: "Self",
            spriteURL: "/images/kellan.png",
            sound: "/sounds/kellan.m4a",
            ability: shrink,
            manaCost: 40
        } as Friend,
        "Columbo": {
            name: "Columbo",
            eachTurnCheck: null,
            abilityName: "Examine",
            abilityDesc: "See what the target will do prematurely.",
            abilityTiming: "After Turn",
            targetType: "AOE",
            spriteURL: "/images/columbo.png",
            sound: "/sounds/columbo.m4a",
            ability: examine,
            manaCost: 5
        } as Friend,
        "Thira": {
            name: "Thira",
            eachTurnCheck: null,
            abilityName: "Time Reversal",
            abilityDesc: "Reset the game and nullify the turn.",
            abilityTiming: "After Turn",
            targetType: "Special",
            spriteURL: "/images/thira.png",
            sound: "/sounds/thira.m4a",
            ability: timeReversal,
            manaCost: 100
        } as Friend,
        "Lucia": {
            name: "Lucia",
            eachTurnCheck: null,
            abilityName: "Revive Song",
            abilityDesc: "Sets a Revive counter for 3 turns. If you die with 1 turn remaining, you revive.",
            abilityTiming: "Before Turn",
            targetType: "Self",
            spriteURL: "/images/lucia.png",
            sound: "/sounds/lucia.m4a",
            ability: reviveSong,
            manaCost: 50
        } as Friend,
        "Humd": {
            name: "Humd",
            eachTurnCheck: null,
            abilityName: "Mango Consumption",
            abilityDesc: "Eat a mango. Heal. Mangos are great. So is Humd. Yum.",
            abilityTiming: "With Attack",
            targetType: "Self",
            spriteURL: "/images/humd.png",
            sound: "/sounds/humd.m4a",
            ability: mangoConsumption,
            manaCost: 20
        } as Friend,
        "Edward": {
            name: "Edward",
            eachTurnCheck: null,
            abilityName: "THE SLAYER",
            abilityDesc: "Gain a non-stackable attack boost.",
            abilityTiming: "Before Turn",
            targetType: "Self",
            spriteURL: "/images/edward.png",
            sound: "/sounds/edward.m4a",
            ability: theSlayer,
            manaCost: 40
        } as Friend,
        "Waldo": {
            name: "Waldo",
            eachTurnCheck: null,
            abilityName: "Hide",
            abilityDesc: "Shrink thrice.",
            abilityTiming: "With Attack",
            targetType: "Self",
            spriteURL: "/images/waldo.png",
            sound: "/sounds/waldo.m4a",
            ability: hide,
            manaCost: 40
        } as Friend,
        "RT Game": {
            name: "RT Game",
            eachTurnCheck: null,
            abilityName: "Drifting",
            abilityDesc: "Drift all over your enemies. Loses less damage with each additional enemy.",
            abilityTiming: "With Attack",
            targetType: "AOE",
            spriteURL: "/images/rtgame.png",
            sound: "/sounds/rtgame.m4a",
            ability: drifting,
            manaCost: 60
        } as Friend,
        "Lemon Alien": {
            name: "Lemon Alien",
            eachTurnCheck: null,
            abilityName: "Lemon Rebirth",
            abilityDesc: "Increase your stats.",
            abilityTiming: "Before Turn",
            targetType: "Self",
            spriteURL: "/images/lemonalien.png",
            sound: "/sounds/lemonalien.m4a",
            ability: lemonRebirth,
            manaCost: 40
        } as Friend,
    })
})