export const enemiesPull:Record<string, EndlessConstructor[]> = {
    'common': [{
        name: "Little Guy",
        img: "/images/littleguys.png",
        baseHP: 20,
        baseAttack: 10,
        baseDefense: 3,
        abilityType: "defense",
        abilityName: "Shrink",
        ability: shrink,
        sound: "/sounds/basehigh.m4a",
        manaCost: 20,
        baseMana: 20,
        title: "Smallish Person",
        desc: "Very little.",
    },{
        name: "Super Blocky Ball",
        img: "/images/superblockyball.png",
        sound: "/sounds/blockyball.m4a",
        baseHP: 24,
        baseAttack: 12,
        baseDefense: 4,
        abilityType: "offense",
        abilityName: "Ball Ram",
        ability: ballRam,
        manaCost: 22,
        baseMana: 25,
        title: "Racer",
        desc: "The fastest ball of the modern era.",
    },{
        name: "Grass Man",
        img: "/images/grassman.png",
        sound: "/sounds/baselow.caf",
        baseHP: 24,
        baseAttack: 13,
        baseDefense: 4,
        abilityType: "offense",
        abilityName: "Grass Cutting",
        ability: grassCut,
        manaCost: 22,
        baseMana: 25,
        title: "NFT",
        desc: "Is it?"
    },{
        name: "Circle",
        img: "/images/circle.png",
        sound: "/sounds/baselow.caf",
        baseHP: 26,
        baseAttack: 13,
        baseDefense: 5,
        abilityType: "offense",
        abilityName: "Circle Smash",
        ability: circleSmash,
        manaCost: 25,
        baseMana: 28,
        title: "NFT",
        desc: "Is it?"
    }],
    'rare': [{
        name: "Lemon Alien",
        img: "/images/lemonalien.png",
        sound: "/sounds/lemonalien.m4a",
        baseHP: 35,
        baseAttack: 12,
        baseDefense: 8,
        abilityType: "defense",
        abilityName: "Lemon Rebirth",
        ability: lemonRebirth,
        manaCost: 28,
        baseMana: 30,
        title: "Venture Capitalist",
        desc: "The bane of my existence."
    },{
        name: "Mini Crossword",
        img: "/images/mini-crossword.png",
        sound: "/sounds/crossword.m4a",
        baseHP: 32,
        baseAttack: 12,
        baseDefense: 8,
        abilityType: "defense",
        abilityName: "Quick Puzzle Confusion",
        ability: miniCrossword,
        manaCost: 30,
        baseMana: 35,
        title: "Puzzle Kid",
        desc: "#FreeTheMini"
    },{
        name: "Waldo",
        img: "/images/waldo.png",
        sound: "/sounds/waldo.m4a",
        baseHP: 38,
        baseAttack: 6,
        baseDefense: 14,
        abilityType: "defense",
        abilityName: "Hide",
        ability: hide,
        manaCost: 30,
        baseMana: 35,
        title: "Hidden Figure",
        desc: "Master of the Little Guys."
    }],
    'superRare': [{
        name: "Alastor",
        img: "/images/alastor.png",
        sound: "/sounds/alastor.m4a",
        baseHP: 45,
        baseAttack: 20,
        baseDefense: 10,
        abilityType: "offense",
        abilityName: "Minion Summon",
        ability: minionSummon,
        manaCost: 35,
        baseMana: 40,
        title: "Radio Demon",
        desc: "Hater of TV and hated by U/Me."
    }],
    'epic': [{
        name: "Maiden O' Luck 1",
        baseMana: 45,
        baseAttack: 20,
        baseDefense: 10,
        abilityType: "offense",
        abilityName: "Make it Wild",
        ability: makeItWild,
        manaCost: 40,
        baseHP: 46,
        img: '/images/maiden-o-luck.webp',
        desc: "The worst horse. Old money horse. Never worked a day in his life horse.",
        title: "Racer",
        sound: '/sounds/maidenoluck.m4a',
    },{
        name: "Joe Biden",
        baseMana: 48,
        baseAttack: 24,
        baseDefense: 10,
        baseHP: 50,
        abilityType: "offense",
        abilityName: "Presidential Authority",
        ability: joeBidenSandman,
        manaCost: 42,
        img: '/images/joebiden.png',
        desc: "The strongest rap battle of history.",
        title: "Sleepyhead",
        sound: '/sounds/joebiden.m4a',
            }],
    'legendary': [{
        name: "Edward (evil)",
        img: "/images/edwardevil.png",
        sound: "/sounds/edward.caf",
        baseHP: 54,
        baseAttack: 26,
        baseDefense: 11,
        abilityType: "offense",
        abilityName: "THE SLAYER",
        ability: theSlayer,
        manaCost: 45,
        baseMana: 52,
        title: "Developer, Friend, and SLAYER",
        desc: "It's me!"
    },{
        name: "Joevil (BOSS)",
        baseAttack: 30,
        baseDefense: 12,
        baseMana: 60,
        abilityType: "offense",
        abilityName: "Reign of Evil",
        ability: evilReign,
        manaCost: 50,
        baseHP: 60,
        img: '/images/joevil.png',
        desc: "This is the end.",
        title: "Birthday Bane",
        sound: '/sounds/joey.m4a',
    }]
}